name: aoc2020
version: 0.1.0.0
github: "sgt/aoc2020"
license: BSD3
author: "Sergei Barbarash"
maintainer: "sgt.sgt@gmail.com"
copyright: "2020 Sergei Barbarash"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/sgt/aoc2020#readme>

ghc-options:
  - -Wall
  - -haddock

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - megaparsec
  - containers
  - text

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2020

tests:
  aoc2020-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2020
      - tasty
      - tasty-hunit
